sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region $AWS_REGION --no-include-email)
  - docker build -t lounasvahti .
  - docker tag lounasvahti:latest $ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/lounasvahti:latest
  - docker push $ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/lounasvahti:latest
  - aws ecs update-service --cluster lounasvahti --service lounasvahti --task-definition lounasvahti --region $AWS_REGION