sudo: required
language: node_js
services:
  - docker
before_install:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - docker build -t lounasvahti .
  - docker tag lounsvahti:latest $ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/lounasvahti:latest
  - docker push $ECR_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/lounasvahti:latest