sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
cache:
  directories:
    - $HOME/.npm
script:
  - docker build -t lounasvahti .
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
